Repository UMC-CHICCHIC/BE, pull requests merged in 2025-08, with the labels that each got.

#20 [Feature] 향수테스트
  src/main/java/chic_chic/spring/client/AIRecommendClient.java
  src/main/java/chic_chic/spring/config/RestTemplateConfig.java
  src/main/java/chic_chic/spring/config/SecurityConfig.java
  src/main/java/chic_chic/spring/converter/TestQuestionConverter.java
  src/main/java/chic_chic/spring/converter/TestResultConverter.java
  src/main/java/chic_chic/spring/domain/TestResult.java
  src/main/java/chic_chic/spring/domain/repository/TestResultRepository.java
  src/main/java/chic_chic/spring/service/TestSubmitService/TestSubmitService.java
  src/main/java/chic_chic/spring/service/TestSubmitService/TestSubmitServiceImpl.java
  src/main/java/chic_chic/spring/web/controller/TestQuestionController.java
  src/main/java/chic_chic/spring/web/controller/TestSubmitController.java
  src/main/java/chic_chic/spring/web/dto/AIRequestDto.java
  src/main/java/chic_chic/spring/web/dto/AIResponseDto.java
  src/main/java/chic_chic/spring/web/dto/AnswerDto.java
  src/main/java/chic_chic/spring/web/dto/OptionDto.java
  src/main/java/chic_chic/spring/web/dto/QuestionDto.java
  src/main/java/chic_chic/spring/web/dto/RecommendedPerfumeDto.java
  src/main/java/chic_chic/spring/web/dto/TestSubmitRequest.java
Labels: :sparkles:feature

#16 [Feat] 제품 리스트, 제품상세
  src/main/java/chic_chic/spring/config/SecurityConfig.java
  src/main/java/chic_chic/spring/domain/Note.java
  src/main/java/chic_chic/spring/domain/Product.java
  src/main/java/chic_chic/spring/domain/ProductNote.java
  src/main/java/chic_chic/spring/domain/ProductNoteId.java
  src/main/java/chic_chic/spring/domain/repository/ProductRepository.java
  src/main/java/chic_chic/spring/web/controller/ProductController.java
  src/main/java/chic_chic/spring/web/controller/ProductDetailController.java
  src/main/java/chic_chic/spring/web/dto/ProductDetailResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductResponse.java
  src/main/java/chic_chic/spring/web/service/ProductDetailService.java
  src/main/java/chic_chic/spring/web/service/ProductService.java
Labels: :sparkles:feature

#14 [Feat] 메인페이지
  src/main/java/chic_chic/spring/config/SecurityConfig.java
  src/main/java/chic_chic/spring/domain/Product.java
  src/main/java/chic_chic/spring/domain/repository/ProductRepository.java
  src/main/java/chic_chic/spring/service/product/ProductService.java
  src/main/java/chic_chic/spring/web/controller/ProductController.java
  src/main/java/chic_chic/spring/web/dto/ProductResponseDto.java
Labels: :sparkles:feature

#36 메인페이지 개인제품추천
  src/main/java/chic_chic/spring/domain/repository/RecommendProductRepository.java
  src/main/java/chic_chic/spring/service/product/HomeProductService.java
  src/main/java/chic_chic/spring/web/controller/HomeController.java
  src/main/java/chic_chic/spring/web/dto/ProductDetailResponse.java
  src/main/java/chic_chic/spring/web/dto/RecommendProductResponseDto.java
Labels: :sparkles:feature

#39 [FIX] 향수 일기장 및 댓글 오류 수정
  src/main/java/chic_chic/spring/domain/Note.java
  src/main/java/chic_chic/spring/domain/Product.java
  src/main/java/chic_chic/spring/domain/repository/PerfumeDiaryCommentRepository.java
  src/main/java/chic_chic/spring/service/ScrapService/ScrapService.java
  src/main/java/chic_chic/spring/service/ScrapService/ScrapServiceImpl.java
  src/main/java/chic_chic/spring/service/perfumediaryservice/PerfumeDiaryServiceImpl.java
  src/main/java/chic_chic/spring/web/controller/PerfumeDiaryController.java
  src/main/java/chic_chic/spring/web/controller/ScrapController.java
  src/main/java/chic_chic/spring/web/dto/CommentRequest.java
  src/main/java/chic_chic/spring/web/dto/CommentResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductDetailResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductListResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductResponse.java
Labels: :hammer:fix

#40 개인추천제품 [FIX]
  src/main/java/chic_chic/spring/config/SecurityConfig.java
  src/main/java/chic_chic/spring/web/controller/HomeController.java
Labels: :hammer:fix

#42 url추가 및 오류수정
  src/main/java/chic_chic/spring/domain/Brand.java
  src/main/java/chic_chic/spring/domain/Product.java
  src/main/java/chic_chic/spring/domain/repository/BrandRepository.java
  src/main/java/chic_chic/spring/service/product/ProductDetailService.java
  src/main/java/chic_chic/spring/web/dto/ProductDetailResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductListResponse.java
  src/main/java/chic_chic/spring/web/dto/ProductResponse.java
  src/main/java/chic_chic/spring/web/dto/RecommendProductResponseDto.java
Labels: :hammer:fix

#46 프로필 이미지 삭제 구현
  .github/workflows/deploy.yml
  src/main/java/chic_chic/spring/config/SecurityConfig.java
  src/main/java/chic_chic/spring/service/ImageService/S3UploaderService.java
  src/main/java/chic_chic/spring/service/ImageService/S3UploaderServiceImpl.java
  src/main/java/chic_chic/spring/service/MemberService/MemberCommandService.java
  src/main/java/chic_chic/spring/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/chic_chic/spring/web/controller/MemberController.java
Labels: :sparkles:feature

#50 로그인 에러 리디랙트 설정
  README.md
  src/main/java/chic_chic/spring/apiPayload/exception/handler/CustomOAuth2SuccessHandler.java
  src/main/java/chic_chic/spring/config/SecurityConfig.java
Labels: :recycle:refactor
